# Workflow name
name: Lint Code Base

# Trigger the workflow on push or pull request events
on: [push, pull_request]

jobs:
  # Define a job named 'build'
  build:
    # Specify the runner environment
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Run Super-Linter to lint the codebase
      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          # Specify the default branch name
          DEFAULT_BRANCH: main
          # Provide the GitHub token for authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Set Super-Linter to skip validation on specific files
          VALIDATE_ALL_CODEBASE: false
          # Exclude README.md from linting
          FILTER_REGEX_EXCLUDE: README\.md
